# Generated by Django 4.2.7 on 2025-04-16 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcas', '0008_rename_farm_id_dcaserrorlog_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCASMessagePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcas.dcasconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='dcas_dcasme_code_92dd14_idx'), models.Index(fields=['priority'], name='dcas_dcasme_priorit_6aff4a_idx')],
            },
        ),
    ]
