# Generated by Django 4.2.7 on 2025-04-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcas', '0009_dcasmessagepriority'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dcasmessagepriority',
            index=models.Index(fields=['code'], name='dcas_dcasme_code_92dd14_idx'),
        ),
        migrations.AddIndex(
            model_name='dcasmessagepriority',
            index=models.Index(fields=['priority'], name='dcas_dcasme_priorit_6aff4a_idx'),
        ),
    ]
