# Generated by Django 4.2.7 on 2025-07-10 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcas', '0011_dcasdownloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCASErrorLogOutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], default='Pending', help_text='The delivery status of the file.', max_length=255, null=True)),
                ('path', models.TextField(blank=True, help_text='Full path to the uploaded file.', null=True)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The time when the file was submitted.', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='The time when the file processing started.', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='The time when the file processing finished.', null=True)),
                ('errors', models.TextField(blank=True, help_text='Errors encountered during file processing.', null=True)),
                ('request', models.ForeignKey(help_text='The DCAS request associated with this error.', on_delete=django.db.models.deletion.CASCADE, related_name='error_log_output_files', to='dcas.dcasrequest')),
            ],
            options={
                'verbose_name': 'Error log file',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
