coverage:
  range: 50..75
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80
    changes: false
    patch:
      default:
        threshold: "10%"
  ignore:
    - "**/migrations/*.py"
    - "django_project/core/settings/*.py"
    - "**/management/commands/*.py"
