# Generated by Django 4.2.7 on 2025-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0047_preferences_api_use_parquet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.BigIntegerField()),
                ('farmgroup_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'gap_farmgroup_farms',
                'managed': False,
            },
        ),
    ]
