# Generated by Django 4.2.7 on 2025-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0048_farmgroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcefile',
            name='format',
            field=models.CharField(choices=[('NETCDF', 'NETCDF'), ('ZARR', 'ZARR'), ('ZIP_FILE', 'ZIP_FILE'), ('PARQUET', 'PARQUET'), ('DUCKDB', 'DUCKDB')], max_length=512),
        ),
    ]
