# Generated by Django 4.2.7 on 2025-03-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0048_farmgroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmGroupRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gap_farmgroup_farms',
                'managed': False,
            },
        ),
    ]
