# Generated by Django 4.2.7 on 2025-04-01 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gap', '0049_farmgrouprelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('description', models.TextField(help_text='Describe your request or interest.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
            ],
            options={
                'verbose_name': 'Sign up request',
                'db_table': 'sign_up_request',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
