# Generated by Django 4.2.7 on 2025-03-30 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0049_farmgrouprelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('description', models.TextField(help_text='Describe your request or interest.')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted at')),
            ],
            options={
                'verbose_name': 'Sign up request',
                'db_table': 'sign_up_request',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
