# Generated by Django 4.2.7 on 2025-04-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0051_signuprequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmshorttermforecast',
            index=models.Index(fields=['farm', 'forecast_date'], name='farm_forecast_date_idx'),
        ),
        migrations.AddIndex(
            model_name='farmshorttermforecastdata',
            index=models.Index(fields=['forecast', 'dataset_attribute', 'value_date'], name='frcst_ds_val_date_idx'),
        ),
        migrations.AddIndex(
            model_name='farmsuitableplantingwindowsignal',
            index=models.Index(fields=['farm', 'generated_date'], name='farm_generated_date_idx'),
        ),
    ]
