# Generated by Django 4.2.7 on 2025-04-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0052_farmshorttermforecast_farm_forecast_date_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='farmshorttermforecastdata',
            name='frcst_ds_val_date_idx',
        ),
    ]
