# Generated by Django 4.2.7 on 2025-04-08 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gap', '0052_farmshorttermforecast_farm_forecast_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='approved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Approved at'),
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'userprofile',
                'ordering': ['user'],
            },
        ),
    ]
