# Generated by Django 4.2.7 on 2025-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0059_collectorsessionprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectorsessionprogress',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ingestorsessionprogress',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='organization',
            field=models.CharField(blank=True, help_text='Name of the organization you represent.', max_length=200, null=True, verbose_name='Organization'),
        ),
    ]
