# Generated by Django 4.2.7 on 2025-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0060_alter_collectorsessionprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Google Analytics ID for tracking.', max_length=255, null=True),
        ),
    ]
