# Generated by Django 4.2.7 on 2025-06-13 07:02

from django.db import migrations, models
import gap.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0061_preferences_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='social_auth_providers',
            field=models.JSONField(default=gap.models.preferences.social_auth_providers_default, help_text='Enables / disables each social-auth provider in the UI. Example: {"google": true, "github": false}'),
        ),
    ]
