# Generated by Django 4.2.7 on 2025-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0062_preferences_social_auth_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INCOMPLETE', 'Incomplete')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
