# Generated by Django 4.2.7 on 2025-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0063_alter_signuprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='job_executor_config',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of JobType and ExecutorConfig; ExecutorConfig will be passed to the Job Executor.', null=True),
        ),
    ]
