# Generated by Django 4.2.7 on 2025-06-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0064_preferences_job_executor_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('resolution', models.CharField(help_text="Resolution of the grid set, e.g., '1km', '10km'.", max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the grid set.', null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration settings for the grid set.', null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.country')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
