# Generated by Django 4.2.7 on 2025-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0065_gridset'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='If the file is deleted, this field will be set.', null=True),
        ),
    ]
