# Generated by Django 4.2.7 on 2025-07-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0067_alter_collectorsession_ingestor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefilecache',
            name='cache_dir',
            field=models.TextField(blank=True, help_text='Path to the cache directory for this source file.', null=True),
        ),
    ]
