# Generated by Django 4.2.7 on 2025-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0069_alter_collectorsession_ingestor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinsightrequest',
            name='method',
            field=models.CharField(choices=[('default', 'Default'), ('tamsat', 'TAMSAT')], default='default', help_text='The method used for crop insight generation', max_length=32),
        ),
        migrations.AddField(
            model_name='preferences',
            name='tamsat_url',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
