# Generated by Django 4.2.7 on 2025-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0069_alter_collectorsession_ingestor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='tamsat_url',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
