# Generated by Django 4.2.7 on 2025-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0070_cropinsightrequest_method_preferences_tamsat_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API'), ('Tio Forecast Collector', 'Tio Forecast Collector'), ('WindBorne Systems API', 'WindBorne Systems API'), ('Cabi Prise Excel', 'Cabi Prise Excel'), ('CBAM Bias Adjusted', 'CBAM Bias Adjusted'), ('DCAS Rules', 'DCAS Rules'), ('Farm Registry', 'Farm Registry'), ('DCAS Message', 'DCAS Message'), ('Hourly Tomorrow.io', 'Hourly Tomorrow.io'), ('Salient Historical', 'Salient Historical'), ('SPW Geoparquet', 'SPW Geoparquet'), ('Google Nowcast', 'Google Nowcast')], default='Tahmo', max_length=512),
        ),
        migrations.AlterField(
            model_name='ingestorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API'), ('Tio Forecast Collector', 'Tio Forecast Collector'), ('WindBorne Systems API', 'WindBorne Systems API'), ('Cabi Prise Excel', 'Cabi Prise Excel'), ('CBAM Bias Adjusted', 'CBAM Bias Adjusted'), ('DCAS Rules', 'DCAS Rules'), ('Farm Registry', 'Farm Registry'), ('DCAS Message', 'DCAS Message'), ('Hourly Tomorrow.io', 'Hourly Tomorrow.io'), ('Salient Historical', 'Salient Historical'), ('SPW Geoparquet', 'SPW Geoparquet'), ('Google Nowcast', 'Google Nowcast')], default='Tahmo', max_length=512),
        ),
    ]
