# Generated by Django 4.2.7 on 2025-09-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0072_alter_collectorsession_ingestor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmgroup',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for the farm group', null=True),
        ),
        migrations.AddField(
            model_name='farmsuitableplantingwindowsignal',
            name='is_sent_before',
            field=models.BooleanField(default=False, help_text='Flag to indicate if the signal has been sent before.'),
        ),
        migrations.AddField(
            model_name='farmsuitableplantingwindowsignal',
            name='prev_reference_date',
            field=models.DateField(blank=True, help_text='The previous reference date used to check the same signal.', null=True),
        ),
    ]
