# Generated by Django 4.2.7 on 2025-07-30 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0070_cropinsightrequest_method_preferences_tamsat_url'),
        ('spw', '0004_spwerrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPWExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the request was created.')),
                ('method', models.CharField(choices=[('default', 'Default'), ('tamsat', 'TAMSAT')], default='default', help_text='The method used for SPW generation', max_length=32)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], default='Pending', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Notes about the SPW execution', null=True)),
                ('errors', models.TextField(blank=True, help_text='Errors encountered during SPW execution', null=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('farm_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gap.farmgroup')),
            ],
            options={
                'verbose_name': 'SPW Execution Log',
                'ordering': ['-requested_at'],
            },
        ),
    ]
