# Generated by Django 4.2.7 on 2025-09-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw', '0005_spwexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='spwoutput',
            name='farm_group_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='spwoutput',
            name='spw_top_message',
            field=models.TextField(blank=True, help_text='Top message that will be shown in SPW output.', null=True),
        ),
    ]
