# Generated by Django 4.2.7 on 2025-09-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw', '0005_spwexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='spwoutput',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spwoutput',
            name='spw_top_message',
            field=models.TextField(blank=True, help_text='Top message that will be shown in SPW output.', null=True),
        ),
        migrations.AlterField(
            model_name='spwoutput',
            name='identifier',
            field=models.CharField(help_text='e.g: Plant NOW Tier 1a. Make sure the result this is coming from SPW R Model.', max_length=512, unique=True),
        ),
    ]
