// measurementData.ts

export interface Product {
    variable_name: string;
    name: string;
  }
  
  export const productList: Product[] = [
    {
      variable_name: 'arable_ground_observation',
      name: 'Automated Weather Stations (Arable) | 2024-2025',
    },
    {
      variable_name: 'tahmo_ground_observation',
      name: 'Automated Weather Stations (TAHMO) (QC/QA) |2018 - 2025| v1',
    },
    {
      variable_name: 'cbam_historical_analysis_bias_adjust',
      name: 'CBAM Daily Reanalysis (Bias-Corrected) | 2012-2023 | v1',
    },
    {
      variable_name: 'cbam_historical_analysis',
      name: 'CBAM Daily Reanalysis (Raw) | 2012-2024 | v2',
    },
    {
      variable_name: 'cbam_shortterm_forecast',
      name: 'CBAM Weather Forecast | Daily | 10-day',
    },
    {
      variable_name: 'cbam_shortterm_hourly_forecast',
      name: 'CBAM Weather Forecast | Hourly | 4-day',
    },
    {
      variable_name: 'disdrometer_ground_observation',
      name: 'Disdrometer (Laser Rain Gauge)',
    },
    {
      variable_name: 'windborne_radiosonde_observation',
      name: 'Radiosonde Observations (Windborne)',
    },
    {
      variable_name: 'salient_seasonal_forecast',
      name: 'Salient Predictions Weather Forecast | Sub-seasonal to Seasonal (8-month)',
    },
    {
      variable_name: 'tamsat_ltn',
      name: 'TAMSAT Precipitation Long-term Normals (20-year)',
    },
  ];
  
  export const attributeMap: Record<string, string[]> = {
    arable_ground_observation: [
      'max_day_temperature',
      'max_relative_humidity',
      'mean_day_temperature',
      'mean_relative_humidity',
      'min_day_temperature',
      'min_relative_humidity',
      'precipitation',
      'precipitation_total',
      'sea_level_pressure',
      'total_evapotranspiration_flux',
      'wind_heading',
      'wind_speed',
      'wind_speed_max',
      'wind_speed_min',
    ],
    tahmo_ground_observation: [
      'average_air_temperature',
      'max_air_temperature',
      'max_relative_humidity',
      'min_air_temperature',
      'min_relative_humidity',
      'precipitation',
      'precipitation_total_chirps',
      'precipitation_total_chirps_qflag',
      'precipitation_total_era5',
      'precipitation_total_qflag',
      'solar_radiation',
    ],
    cbam_historical_analysis_bias_adjust: [
      'max_temperature',
      'min_temperature',
      'total_rainfall',
      'total_solar_irradiance',
    ],
    cbam_historical_analysis: [
      'average_solar_irradiance',
      'average_vapor_pressure',
      'max_day_temperature',
      'max_night_temperature',
      'max_relative_humidity',
      'max_temperature',
      'min_day_temperature',
      'min_night_temperature',
      'min_relative_humidity',
      'min_temperature',
      'total_evapotranspiration_flux',
      'total_rainfall',
      'total_solar_irradiance',
      'wind_speed_avg',
    ],
    cbam_shortterm_forecast: [
      'flood_index',
      'humidity_maximum',
      'humidity_minimum',
      'max_temperature',
      'min_temperature',
      'precipitation_probability',
      'solar_radiation',
      'total_evapotranspiration_flux',
      'total_rainfall',
      'weather_code',
      'wind_speed_avg',
    ],
    cbam_shortterm_hourly_forecast: [
      'flood_index',
      'humidity',
      'precipitation_probability',
      'solar_radiation',
      'temperature',
      'total_evapotranspiration_flux',
      'total_rainfall',
      'weather_code',
      'wind_direction',
      'wind_speed',
    ],
    disdrometer_ground_observation: [
      'atmospheric_pressure',
      'depth_of_water',
      'electrical_conductivity_of_precipitation',
      'electrical_conductivity_of_water',
      'lightning_distance',
      'precipitation',
      'precipitation_total',
      'relative_humidity',
      'shortwave_radiation',
      'soil_moisture_content',
      'soil_temperature',
      'surface_air_temperature',
      'wind_gusts',
      'wind_heading',
      'wind_speed',
    ],
    default: [
      'humidity_maximum',
      'humidity_minimum',
      'max_temperature',
      'min_temperature',
      'precipitation_probability',
      'solar_radiation',
      'total_evapotranspiration_flux',
      'total_rainfall',
      'wind_speed_avg',
    ],
    windborne_radiosonde_observation: [
      'atmospheric_pressure',
      'relative_humidity',
      'specific_humidity',
      'temperature',
    ],
    salient_seasonal_forecast: [
      'max_temperature',
      'max_temperature_anom',
      'max_temperature_clim',
      'min_temperature',
      'min_temperature_anom',
      'min_temperature_clim',
      'precipitation',
      'precipitation_anom',
      'precipitation_clim',
      'relative_humidity',
      'relative_humidity_anom',
      'relative_humidity_clim',
      'solar_radiation',
      'solar_radiation_anom',
      'solar_radiation_clim',
      'temperature',
      'temperature_anom',
      'temperature_clim',
      'wind_speed',
      'wind_speed_anom',
      'wind_speed_clim',
    ],
    tamsat_ltn: [
      'precipitation_total',
    ],
  };
  