version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  worker:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../:/home/web/project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  celery_beat:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../:/home/web/project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  dev:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    entrypoint: []
    env_file:
      - .env
    volumes:
      - ../:/home/web/project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    links:
      - db
      - worker
      - plumber

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  plumber:
    build:
      context: ../
      dockerfile: deployment/plumber/Dockerfile
    env_file:
      - .env
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/plumber_data:/home/web/plumber_data
      - ./volumes/media:/home/web/media
    links:
      - db
      - redis
