version: '3.9'

volumes:
  static-data:
  media-data:
  conf-data:
  database:
  nginx-cache:
  backups-data:
  data-volume:
  minio-data:
  hyrax-data:

x-common-django:
  &default-common-django
  image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}:${DJANGO_TAG:-1.0.0}
  environment:
    - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-core.settings.dev}

    - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
    - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}

    - DATABASE_NAME=${DATABASE_NAME:-django}
    - DATABASE_USERNAME=${DATABASE_USERNAME:-docker}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD:-docker}
    - DATABASE_HOST=${DATABASE_HOST:-db}
    - DATABASE_PORT=${DATABASE_PORT:-5432}
    - REDIS_HOST=${REDIS_HOST:-redis}
    - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}

    - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
    - SENTRY_DSN=${SENTRY_DSN:-}
    # s3 variable
    - S3_AWS_ACCESS_KEY_ID={S3_AWS_ACCESS_KEY_ID:-minio_tomorrownow}
    - S3_AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY:-minio_tomorrownow}
    - S3_AWS_ENDPOINT=${S3_AWS_ENDPOINT}
    - S3_AWS_BUCKET_NAME=${S3_AWS_BUCKET_NAME:-tomorrownow}
    - INITIAL_FIXTURES=${INITIAL_FIXTURES:-}
  volumes:
    - static-data:/home/web/static
    - media-data:/home/web/media
  restart: on-failure

services:
  redis:
    image: bitnami/redis:7.0.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}

  db:
    image: kartoza/postgis:14-3.3
    volumes:
      - data-volume:/opt/postgres/data
    environment:
      - DATADIR=/opt/postgres/data
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DBNAME=${DATABASE_NAME:-django}
      - POSTGRES_USER=${DATABASE_USERNAME:-docker}
      - POSTGRES_PASS=${DATABASE_PASSWORD:-docker}

  dbbackups:
    image: kartoza/postgis:14-3.3
    volumes:
      - data-volume:/backups
    environment:
      - POSTGRES_DBNAME=${DATABASE_NAME:-django}
      - POSTGRES_USER=${DATABASE_USERNAME:-docker}
      - POSTGRES_PASS=${DATABASE_PASSWORD:-docker}

  django:
    <<: *default-common-django
    command: 'uwsgi --ini /uwsgi.conf'
    links:
      - db
      - worker

  worker:
    <<: *default-common-django
    entrypoint: [ ]
    command: 'celery -A core worker -l info'
    links:
      - db
      - redis
      - celery_beat

  celery_beat:
    <<: *default-common-django
    entrypoint: [ ]
    command: 'celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler'
    links:
      - db
      - redis

  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - conf-data:/etc/nginx/conf.d:ro
      - static-data:/home/web/static
      - media-data:/home/web/media
      - nginx-cache:/home/web/nginx_cache
    links:
      - django

  dev:
    <<: *default-common-django
    entrypoint: [ ]
    volumes:
      - static-data:/home/web/static
      - media-data:/home/web/media
    links:
      - db
      - redis

  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    command: minio server /data --console-address ":9001"
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: ${S3_AWS_ACCESS_KEY_ID:-minio_tomorrownow}
      MINIO_ROOT_PASSWORD: ${S3_AWS_SECRET_ACCESS_KEY:-minio_tomorrownow}
      MINIO_HTTP_TRACE: /opt/bitnami/minio/log/minio.log
    volumes:
      - minio-data:/data
    restart: always

  hyrax:
    image: opendap/hyrax:1.17.0-122
    ports:
      - "8181:8080"
    volumes:
      - hyrax-data:/usr/share/hyrax
    restart: always
