version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  worker:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ${PWD}
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static

  dev:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ${PWD}
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    entrypoint: []
    env_file:
      - .env
    volumes:
      - ../:/home/web/project
      - ./volumes/static:/home/web/static
    links:
      - db
      - worker
      - plumber

  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    command: minio server /data --console-address ":9001"
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_AWS_ACCESS_KEY_ID:-minio_tomorrownow}
      MINIO_ROOT_PASSWORD: ${MINIO_AWS_SECRET_ACCESS_KEY:-minio_tomorrownow}
      MINIO_HTTP_TRACE: /opt/bitnami/minio/log/minio.log
    volumes:
      - ./volumes/minio_data:/data
    restart: always

  plumber:
    build:
      context: ../
      dockerfile: deployment/plumber/Dockerfile
    env_file:
      - .env
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
    ports:
      - "8282:8282"
    links:
      - db
      - redis
