version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  worker:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  celery_beat:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  nginx:
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    ports:
      - "${HTTP_PORT:-8888}:80"
    links:
      - django

  dev:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    ports:
      # for django test server
      - "5000:8080"
      # for ssh
      - "5001:22"
    links:
      - db
      - redis
      - worker
      - celery_beat
    entrypoint: [ ]

  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    command: minio server /data --console-address ":9001"
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_AWS_ACCESS_KEY_ID:-minio_tomorrownow}
      MINIO_ROOT_PASSWORD: ${MINIO_AWS_SECRET_ACCESS_KEY:-minio_tomorrownow}
      MINIO_HTTP_TRACE: /opt/bitnami/minio/log/minio.log
    volumes:
      - ./volumes/minio_data:/data
    restart: always
