# Specific configuration for development environment

volumes:
  media-data:
  minio-data:

# Exactly the same as production but for dev env, we expose the port and uses
# different port for the web.
version: '3.4'
services:

  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    command: minio server /data --console-address ":9001"
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
      - MINIO_HTTP_TRACE
    volumes:
      - minio-data:/data
    restart: always

  dev:
    image: ${APP_IMAGE}:dev
    container_name: "dev"
    links:
      - db
      - redis
      - minio
    volumes:
      - media-data:/home/web/media
      - ./docker/Dockerfile:/home/web/django_project/Dockerfile
      - ./docker/requirements.txt:/home/web/django_project/requirements.txt
      - ./docker/requirements-dev.txt:/home/web/django_project/requirements-dev.txt
      - ./production_prep_check.py:/home/web/django_project/production_prep_check.py
    environment:
      # editable in .env
      - DATABASE_NAME=django
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=docker
      - DATABASE_HOST=db
      - DJANGO_SETTINGS_MODULE=core.settings.test
      - SECRET_KEY=SECRET_KEY

      # Redis config
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis_password

      # Email where alters should be sent. This will be used by let's encrypt and as the django admin email.
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@example.com
      - SENTRY_DSN=
      - SENTRY_ENVIRONMENT=staging

      # Minio
      - MINIO_AWS_ACCESS_KEY_ID=minio_user
      - MINIO_AWS_SECRET_ACCESS_KEY=minio_password
      - MINIO_AWS_ENDPOINT_URL=http://minio:9000/
      - MINIO_AWS_BUCKET_NAME=tomorrownow
      - MINIO_AWS_DIR_PREFIX=dev/media
    entrypoint: [ ]
    ports:
      # for django test server
      - "5000:5000"