version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  worker:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ${PWD}
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/hyrax_data:/home/web/opendap

  celery_beat:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ${PWD}
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/hyrax_data:/home/web/opendap

  dev:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ${PWD}
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    entrypoint: []
    volumes:
      - ../:/home/web/project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/hyrax_data:/home/web/opendap
    links:
      - db
      - worker

  django:
    build:
      context: ${PWD}
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/hyrax_data:/home/web/opendap

  minio:
    volumes:
      - ./volumes/minio_data:/data

  hyrax:
    entrypoint: [ "/custom_entrypoint.sh" ]
    volumes:
      - ./volumes/hyrax_data:/usr/share/hyrax
      - ./hyrax/site.conf:/etc/bes/site.conf:ro
      - ./hyrax/entrypoint.sh:/custom_entrypoint.sh
    links:
      - minio
      - dev
      - worker
