# Generated by Django 4.2.7 on 2025-04-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_messagetemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='application',
            field=models.CharField(choices=[('PRISE', 'PRISE'), ('DCAS', 'DCAS')], default='PRISE', max_length=512),
        ),
    ]
