# Generated by Django 4.2.7 on 2025-09-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_messagetemplate_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='application',
            field=models.CharField(choices=[('PRISE', 'PRISE'), ('DCAS', 'DCAS'), ('SPW', 'SPW')], default='PRISE', max_length=512),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='group',
            field=models.CharField(blank=True, choices=[('Start of Season', 'Start of Season'), ('PRISE Time To Action 1 - Beginning of the month', 'PRISE Time To Action 1 - Beginning of the month'), ('PRISE Time To Action 2 - Second half of the month', 'PRISE Time To Action 2 - Second half of the month'), ('End of season', 'End of season')], max_length=512, null=True),
        ),
    ]
