# Generated by Django 4.2.7 on 2025-04-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(default='public', max_length=255, verbose_name='Schema name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Table Usage',
                'verbose_name_plural': 'Table Usage',
                'ordering': ['-created_on'],
            },
        ),
    ]
