# Generated by Django 4.2.7 on 2025-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tableusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectStorageManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(help_text='Unique name for the connection to the object storage.', max_length=128, unique=True, verbose_name='Connection Name')),
                ('protocol', models.CharField(choices=[('S3', 'S3')], default='S3', max_length=255)),
                ('access_key_id_var', models.CharField(max_length=255, verbose_name='Access Key ID Variable')),
                ('secret_access_key_var', models.CharField(max_length=255, verbose_name='Secret Access Key Variable')),
                ('bucket_name', models.CharField(max_length=255, verbose_name='Bucket Name')),
                ('endpoint_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endpoint URL')),
                ('region_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region Name')),
                ('directory_prefix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Directory Prefix')),
                ('use_env_vars', models.BooleanField(default=True, help_text='If checked, the bucket_name, endpoint_url, region_name, directory_prefix will be retrieved from environment variables.', verbose_name='Use Environment Variables')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
    ]
