# Generated by Django 4.2.7 on 2025-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tableusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskContextIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=512)),
            ],
        ),
    ]
