# Generated by Django 4.2.7 on 2025-07-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_objectstoragemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text='Path of the file/folder that was deleted.')),
                ('is_directory', models.BooleanField(default=False, help_text='Indicates if the deletion was for a directory.', verbose_name='Is Directory')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deleted At')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], default='Pending', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('errors', models.TextField(blank=True, help_text='Any errors that occurred during deletion.', null=True, verbose_name='Errors')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Statistics about the deletion process.', null=True, verbose_name='Deletion Stats')),
                ('object_storage_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_logs', to='core.objectstoragemanager')),
            ],
        ),
    ]
