# Generated by Django 4.2.7 on 2025-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deletionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstoragemanager',
            name='protocol',
            field=models.CharField(choices=[('S3', 'S3'), ('GCS', 'GCS')], default='S3', max_length=255),
        ),
    ]
