# Generated by Django 4.2.7 on 2025-05-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_api', '0006_alter_userfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='output_file_size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
