# Generated by Django 4.2.7 on 2025-06-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gap_api', '0007_apirequestlog_output_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the analysis.', primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('DataRequest', 'Data Request')], default='DataRequest', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], default='Pending', max_length=50)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('output_json', models.JSONField(blank=True, default=dict, help_text='Output JSON data from the job.', null=True)),
                ('queue_name', models.CharField(blank=True, help_text='Name of the queue where the job is submitted.', max_length=255, null=True)),
                ('wait_type', models.IntegerField(choices=[(0, 'No wait'), (1, 'Wait for completion'), (2, 'Wait for completion asynchronously')], default=0, help_text='Type of wait for the job to complete.')),
                ('task_id', models.CharField(blank=True, help_text='ID of the task in the background processing system.', max_length=512, null=True)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('output_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_output_file', to='gap_api.userfile')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the job.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
