# Generated by Django 4.2.7 on 2025-06-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text="A short, unique identifier for the page (e.g. 'dcas_csv').", max_length=100, unique=True)),
                ('groups', models.ManyToManyField(help_text='Which auth groups are allowed to view this page.', related_name='page_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Page Permission',
                'verbose_name_plural': 'Page Permissions',
                'db_table': 'frontend_page_permission',
            },
        ),
    ]
