# Generated by Django 4.2.7 on 2025-06-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyMetadata',
            fields=[
                ('digest', models.CharField(db_index=True, help_text='The unique API key token.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
